version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14

sphnix:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt