name: CI — pytest (Ubuntu + Windows)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch: {}

jobs:
  test:
    name: Test on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.10, 3.11, 3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip (Linux)
        if: runner.os != 'Windows'
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache pip (Windows)
        if: runner.os == 'Windows'
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\AppData\Local\pip\Cache
          key: windows-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            windows-pip-

      - name: Install dependencies (Linux)
        if: runner.os != 'Windows'
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pytest pandas nltk
          fi
        shell: bash

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if (Test-Path -Path 'requirements.txt') {
            pip install -r requirements.txt
          } else {
            pip install pytest pandas nltk
          }
        shell: pwsh

      - name: Prepare NLTK data (Linux)
        if: runner.os != 'Windows'
        run: |
          python - <<'PY'
          import nltk, os
          d = os.path.join(os.environ.get("RUNNER_TEMP", "/tmp"), "nltk_data")
          os.makedirs(d, exist_ok=True)
          nltk.download(['punkt','averaged_perceptron_tagger','wordnet','stopwords'], download_dir=d)
          print("NLTK data installed to:", d)
          PY
          echo "NLTK_DATA=${RUNNER_TEMP}/nltk_data" >> $GITHUB_ENV
        shell: bash

      - name: Prepare NLTK data (Windows)
        if: runner.os == 'Windows'
        run: |
          $pyfile = Join-Path $env:RUNNER_TEMP "nltk_setup.py"
          @"
          import nltk, os
          d = os.path.join(os.environ.get('RUNNER_TEMP', r'C:\\windows\\temp'), 'nltk_data')
          os.makedirs(d, exist_ok=True)
          nltk.download(['punkt','averaged_perceptron_tagger','wordnet','stopwords'], download_dir=d)
          print('NLTK data installed to:', d)
          "@ | Out-File -FilePath $pyfile -Encoding utf8
          python $pyfile
          $nltkPath = Join-Path $env:RUNNER_TEMP "nltk_data"
          Add-Content -Path $env:GITHUB_ENV -Value ("NLTK_DATA=$nltkPath")
        shell: pwsh

      - name: Show system info
        run: |
          python -V
          python -c "import sys, platform; print(platform.platform(), platform.machine())"
          pip --version
          pip list --format=columns
        shell: bash

      - name: Run tests with pytest
        env:
          # Ensure NLTK_DATA is visible to the pytest process (set by previous steps)
          NLTK_DATA: ${{ runner.temp }}/nltk_data
        run: |
          pytest -q
        shell: bash
